server:
  port: 8084

spring:
  application:
    name: feign-service

eureka:
  client:
    service-url:
      defaultZone: http://ssssyy:123456@localhost:8080/eureka/
  instance:
    ipAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
